# Generated by Django 3.0.4 on 2020-03-30 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='destination',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
